[package]
name = "relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9.3"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.1"
serde = "1.0.176"
serde_json = "1"
hex = "0.4"
lazy_static = "1.4"
ic-websocket-cdk = { git = "https://github.com/omnia-network/ic-websocket-cdk-rs", rev = "a1d05625f96faa12cad484afcdd01ddad39bb28c" }
bitcoin_hashes = { version = "0.10", features = ["serde"] }

# comment out or delete `dev` feature if you want to deploy production dynamic canisters
[features]
default = ["dev"]
dev = []
